volumes:
  pg-data:
    name: keycloak-pg-data

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: passw0rd
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    environment:
      - KC_HTTP_PORT=8080
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=passw0rd
      - KC_LOG_LEVEL=INFO,org.keycloak:DEBUG,org.keycloak.storage.ldap:TRACE
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    depends_on:
      - openldap
      - postgres

  openldap:
    image: bitnami/openldap:latest
    environment:
      - BITNAMI_DEBUG=true
      - LDAP_CONFIG_ADMIN_ENABLED=yes
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_ROOT=dc=example,dc=org
      - LDAP_ADMIN_DN=cn=admin,dc=example,dc=org
      - LDAP_EXTRA_SCHEMAS=cosine,inetorgperson,nis,memberof
      - LDAP_CUSTOM_LDIF_DIR=/ldifs
    ports:
      - "1389:1389"
      - "636:636"
    volumes:
      - './openldap/ldifs:/ldifs'
      - './openldap/schema/memberof.ldif:/opt/bitnami/openldap/etc/schema/memberof.ldif'

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=#PYTHON2BASH:[{"openldap":[{"server":[{"port":1389}]}]}]
      - PHPLDAPADMIN_HTTPS=false
      - PHPLDAPADMIN_LDAP_CLIENT_TLS=false
    ports:
      - "8081:80"
    depends_on:
      - openldap
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    volumes:
       - ./pgadmin/pgpass:/pgadmin4/pgpass
       - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres 
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.org"
      PGADMIN_DEFAULT_PASSWORD: "pass"
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
      PGADMIN_DISABLE_POSTFIX: "True"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    entrypoint: /bin/sh -c "chmod 600 /pgadmin4/pgpass; /entrypoint.sh;"